### ISSUE TITLE
API to declare "must load" assets

### ISSUE THREAD

**Issue by tony56a** [thale5/LoadingScreenMod#1]
Bit of a random request, but I'm trying out your mod, and I've just realized that, since my mod requires the use of props but are instantiating them as gameobjects, said props might not count as enabled, and I'm currently seeing errors since they're not loaded into the game. Would it be possible to have some sort of mechanism to declare assets that must be loaded into the level?

**Comment by thale5** [comment]
Hi, could you explain a bit more? Loading Screen Mod is currently able to load assets that are enabled in Content Manager and assets that the save game lists as required. I guess your props do not fall into these two categories?

An API could be possible of course but how does your mod work with the default loader then?

**Comment by tony56a** [comment]
The way [mark-a-route](https://github.com/tony56a/MarkARoute) works is that it creates a bunch of gameobjects using the meshes from relevant props. Since they're not actually being placed as props, or being used in any in-game mechanisms, it seems like they don't count as "loaded assets". 

As for how this could be implemented, maybe have a JSON file (XML works too, but in case KV stores are necessary, having it as JSON would make it easier to do ) that contains a list of prop names that needs to be loaded. Mods could write in the props they want to load, and Loading Screen Mod would check against that, in addition to existing checks. Only issue I see here would be that a reload would probably be required on first load, but I'm ok with something like that.

**Comment by thale5** [comment]
So, those are custom props that load fine when enabled in Content Manager but you would like to automate the loading? Not a bad idea.

I haven't looked at Mark-a-Route codes earlier but now that you mention it, it looks interesting. I will look at it over the weekend.

I would like to avoid using files. They sometimes stay behind and haunt you later when unprepared. Do you process the OnCreated event? If I open a public method API for you, that would be the perfect time to hand over some asset names for loading.

Please notice that the above would work only when 'Load used assets' is enabled because that enables usage tracking. It is enabled by default, though.

**Comment by tony56a** [comment]
Hi, 

Just wondering, was this ever implemented?

**Comment by thale5** [comment]
Hi, sorry for the late reply. No, this issue never made actual progress. 

    On Friday, October 21, 2016 7:39 PM, Tony Du <notifications@github.com> wrote:
 

 Hi, Just wondering, was this ever implemented? —
